# Generated by Django 5.2.11 on 2026-02-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nethriq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='video_url',
            field=models.URLField(blank=True, help_text='S3 URL for production, or absolute local path for testing.', max_length=1000, null=True),
        ),
    ]
