"""
Django settings for nethriq project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(file_path: Path, override: bool = False) -> None:
    """Minimal dotenv loader to avoid external runtime requirements in settings."""
    if not file_path.exists():
        return

    for raw_line in file_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")

        if not key:
            continue
        if override:
            os.environ[key] = value
        else:
            os.environ.setdefault(key, value)


# Load environment variables from project-level dotenv files.
# `.env.local` can override `.env` for machine-specific configuration.
_load_env_file(BASE_DIR / '.env')
_load_env_file(BASE_DIR / '.env.local', override=True)


# Helper functions for environment variable parsing
def _env_bool(name: str, default: bool) -> bool:
    """Parse environment variable as boolean."""
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_int(name: str, default: int, minimum: int) -> int:
    """Parse environment variable as integer with minimum."""
    value = os.getenv(name)
    if value is None:
        return default
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        return default
    return max(parsed, minimum)


def _env_float(name: str, default: float, minimum: float) -> float:
    """Parse environment variable as float with minimum."""
    value = os.getenv(name)
    if value is None:
        return default
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return default
    return max(parsed, minimum)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise RuntimeError('SECRET_KEY environment variable is required.')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', False)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,.ngrok-free.dev').split(',')
    if host.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nethriq',
    'django_celery_beat',
    'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nethriq.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nethriq.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    try:
        import dj_database_url  # type: ignore
    except ImportError:
        if DATABASE_URL.startswith('sqlite:///'):
            sqlite_path = DATABASE_URL.replace('sqlite:///', '', 1)
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': sqlite_path,
                }
            }
        else:
            raise RuntimeError(
                'DATABASE_URL provided but dj-database-url is not installed. '
                'Install dj-database-url or use a sqlite:/// URL.'
            )
    else:
        DATABASES = {
            'default': dj_database_url.parse(
                DATABASE_URL,
                conn_max_age=600,
                conn_health_checks=True,
            ),
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('SQLITE_PATH', str(BASE_DIR / 'db.sqlite3')),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (User uploads: videos, etc.)
# https://docs.djangoproject.com/en/5.2/ref/settings/#media-root
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = 'media/'

# File Storage Configuration
# Django 5 uses STORAGES; DEFAULT_FILE_STORAGE alone is not sufficient.
if DEBUG:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

    # AWS S3 / Cloudflare R2 Configuration
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'auto')
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')
    AWS_S3_ADDRESSING_STYLE = os.getenv('AWS_S3_ADDRESSING_STYLE', 'path')
    AWS_S3_SIGNATURE_VERSION = os.getenv('AWS_S3_SIGNATURE_VERSION', 's3v4')
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = _env_bool('AWS_QUERYSTRING_AUTH', False)
    AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN')
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}

    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================================
# Celery Configuration (Message Queue & Async Tasks)
# ============================================================================

# Railway commonly provides REDIS_URL. Keep explicit CELERY_* vars highest priority.
_default_redis_url = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
_celery_broker_override = os.getenv('CELERY_BROKER_URL')
_celery_result_override = os.getenv('CELERY_RESULT_BACKEND')

# Broker configuration: Redis
CELERY_BROKER_URL = _celery_broker_override or _default_redis_url

# Result backend: can use Redis or Django DB (django-celery-results)
# Using Redis for speed; switch to 'django-db' if persistence needed across restarts
CELERY_RESULT_BACKEND = _celery_result_override or _default_redis_url

# Task serialization (JSON is safe and standard)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Timezone for scheduled tasks
CELERY_TIMEZONE = 'UTC'

# Task configuration
CELERY_TASK_TRACK_STARTED = True  # Track when tasks start execution
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minute hard limit per task
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minute soft limit (allows graceful shutdown)

# Worker configuration
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Don't grab multiple tasks at once
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # Restart worker after 1000 tasks (memory safety)


# ============================================================================
# File Upload Configuration (Trap 4: Large File Handling)
# ============================================================================
# Default: 2.5MB is too small for video uploads
# Configure memory buffer for streaming large files to S3
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('FILE_UPLOAD_MAX_MEMORY_SIZE', 100 * 1024 * 1024))  # 100MB default
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('DATA_UPLOAD_MAX_MEMORY_SIZE', 100 * 1024 * 1024))  # 100MB for form data

# Temporary file storage location for uploads exceeding memory threshold
_upload_temp_dir = os.getenv('FILE_UPLOAD_TEMP_DIR', '/tmp/django_uploads')
os.makedirs(_upload_temp_dir, exist_ok=True)
FILE_UPLOAD_TEMP_DIR = _upload_temp_dir


# ============================================================================
# Email Delivery Configuration
# ============================================================================

RUNNING_TESTS = any(arg in {'test', 'pytest'} for arg in sys.argv)

EMAIL_DELIVERY_ENABLED = _env_bool('EMAIL_DELIVERY_ENABLED', not RUNNING_TESTS)
EMAIL_DELIVERY_MAX_ATTACHMENT_BYTES = _env_int(
    'EMAIL_DELIVERY_MAX_ATTACHMENT_BYTES',
    25 * 1024 * 1024,
    1,
)

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = _env_int('EMAIL_PORT', 25, 1)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', False)
EMAIL_USE_SSL = _env_bool('EMAIL_USE_SSL', False)
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    # Prefer TLS when both are accidentally enabled.
    EMAIL_USE_SSL = False
EMAIL_TIMEOUT = _env_int('EMAIL_TIMEOUT', 30, 1)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@nethriq.local')


# ============================================================================
# Stub Claim Flow Configuration
# ============================================================================

# Branding value for claim/delivery communications.
CLUB_NAME = os.getenv('CLUB_NAME', 'PB Vision Athletics')

# Default one-time claim link validity window.
CLAIM_LINK_TTL_HOURS = _env_float('CLAIM_LINK_TTL_HOURS', 24.0, 0.25)
CLAIM_LINK_TTL_SECONDS = int(CLAIM_LINK_TTL_HOURS * 3600)

# Optional explicit frontend origin for claim links.
# Example: https://app.example.com
CLAIM_URL_BASE = os.getenv('CLAIM_URL_BASE', '').strip()

