#!/usr/bin/env python3
"""
Player Analytics Spreadsheet Generator

Generates polished per-player analytics spreadsheets in Excel format with:
- Summary sheet with player KPIs
- Serve analysis with depth/height distributions
- Return analysis  
- Kitchen performance by role and perspective
- Best shots sheet with shot descriptions
- Raw shot data (hidden sheet)
"""

import csv
import json
from pathlib import Path
from typing import Dict, List
import xlsxwriter


class SpreadsheetGenerator:
    """Generates template-based player analytics spreadsheets."""

    GRADE_COLORS = {
        "Pro": "#06B6D4",          # Cyan
        "Advanced": "#10B981",      # Green
        "Intermediate": "#F59E0B",  # Amber
        "Beginner": "#EF4444",      # Red
    }

    def __init__(self, data_dir: str, output_dir: str = None):
        """
        Initialize generator with data directory.
        
        Args:
            data_dir: Directory containing CSV files
            output_dir: Output directory for Excel files (defaults to reports/ in parent)
        """
        self.data_dir = Path(data_dir)
        
        if output_dir is None:
            output_dir = self.data_dir / "reports"
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # Load data
        self.player_averages = self._load_csv("player_averages.csv")
        self.shot_level_data = self._load_csv("shot_level_data.csv")
        self.kitchen_role_stats = self._load_csv("kitchen_role_stats.csv")
        self.player_best_shots = self._load_csv("player_best_shots.csv")
        self.video_links = self._load_video_links()

    def _load_video_links(self) -> Dict:
        """Load video links JSON if present (generated by video_clipper)."""
        links_path = self.data_dir / "video_links.json"
        if not links_path.exists():
            return {}
        try:
            with open(links_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, OSError):
            return {}

    def _load_csv(self, filename: str) -> List[Dict]:
        """Load CSV file into list of dictionaries."""
        filepath = self.data_dir / filename
        data = []
        try:
            with open(str(filepath), "r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                data = list(reader)
        except FileNotFoundError:
            print(f"Warning: {filename} not found at {filepath}")
        return data

    def _get_player_data(self, player_id: int) -> Dict:
        """Extract player-specific data from all sources."""
        player_row = next(
            (r for r in self.player_averages if int(r["player_id"]) == player_id),
            None
        )
        if not player_row:
            raise ValueError(f"Player {player_id} not found in data")

        player_shots = [r for r in self.shot_level_data if int(r["player_id"]) == player_id]
        player_kitchen = [r for r in self.kitchen_role_stats if int(r["player_id"]) == player_id]

        return {
            "info": player_row,
            "shots": player_shots,
            "kitchen": player_kitchen,
        }

    def _get_player_video_links(self, player_id: int) -> Dict:
        """Return serve/return and best-shot links for a player if available."""
        if not self.video_links:
            return {"serve": None, "return": None, "best_shots": []}

        player_key = f"player_{player_id}"
        serve_key = f"{player_key}_serve_context"
        return_key = f"{player_key}_return_context"

        serve_link = self.video_links.get(serve_key, {}).get("link")
        return_link = self.video_links.get(return_key, {}).get("link")

        best_shots = []
        for key, payload in self.video_links.items():
            if key.startswith(f"{player_key}_best_shot_"):
                link = payload.get("link") if isinstance(payload, dict) else None
                if link:
                    best_shots.append((key, link))

        best_shots.sort(key=lambda x: x[0])

        return {
            "serve": serve_link,
            "return": return_link,
            "best_shots": best_shots,
        }

    def _safe_float(self, value, default=0.0) -> float:
        """Safely convert a value to float, returning default if empty or invalid."""
        if not value or value == '""' or str(value).strip() == "":
            return default
        try:
            return float(value)
        except (ValueError, TypeError):
            return default

    def _calculate_shot_stats(self, shots: List[Dict]) -> Dict:
        """Calculate statistics from shot-level data."""
        serves = [s for s in shots if s["shot_role"] == "serve"]
        returns = [s for s in shots if s["shot_role"] == "return"]

        def safe_avg(values, key):
            nums = [float(v[key]) for v in values if v[key]]
            return sum(nums) / len(nums) if nums else 0

        serve_stats = {
            "count": len(serves),
            "avg_depth": safe_avg(serves, "depth"),
            "avg_height": safe_avg(serves, "height_over_net"),
        }

        return_stats = {
            "count": len(returns),
            "avg_depth": safe_avg(returns, "depth"),
            "avg_height": safe_avg(returns, "height_over_net"),
        }

        return {
            "serve": serve_stats,
            "return": return_stats,
        }

    def _calculate_depth_distribution(self, shots: List[Dict], shot_role: str) -> Dict:
        """Distribute shots by depth buckets."""
        filtered = [s for s in shots if s["shot_role"] == shot_role]
        depths = [float(s["depth"]) for s in filtered if s["depth"]]

        if not depths:
            return {"Kitchen (0-6)": 0, "Mid (6-18)": 0, "Deep (18+)": 0}

        return {
            "Kitchen (0-6)": len([d for d in depths if d < 6]),
            "Mid (6-18)": len([d for d in depths if 6 <= d < 18]),
            "Deep (18+)": len([d for d in depths if d >= 18]),
        }

    def _calculate_height_distribution(self, shots: List[Dict], shot_role: str) -> Dict:
        """Distribute shots by height buckets."""
        filtered = [s for s in shots if s["shot_role"] == shot_role]
        heights = [float(s["height_over_net"]) for s in filtered if s["height_over_net"]]

        if not heights:
            return {"Low (0-3)": 0, "Mid (3-5)": 0, "High (5+)": 0}

        return {
            "Low (0-3)": len([h for h in heights if h < 3]),
            "Mid (3-5)": len([h for h in heights if 3 <= h < 5]),
            "High (5+)": len([h for h in heights if h >= 5]),
        }

    def generate(self, player_id: int):
        """Generate analytics spreadsheet for a player."""
        player_data = self._get_player_data(player_id)
        info = player_data["info"]
        
        # Create workbook
        output_file = self.output_dir / f"player_{player_id}_analysis.xlsx"
        workbook = xlsxwriter.Workbook(str(output_file))
        
        # Define formats
        header_fmt = workbook.add_format({
            "bold": True,
            "bg_color": "#1F2937",
            "font_color": "white",
            "border": 1,
            "align": "center",
            "valign": "vcenter",
            "font_size": 12,
        })

        title_fmt = workbook.add_format({
            "bold": True,
            "font_size": 16,
            "align": "left",
            "valign": "vcenter",
        })

        label_fmt = workbook.add_format({
            "bold": True,
            "bg_color": "#F3F4F6",
            "border": 1,
        })

        value_fmt = workbook.add_format({
            "border": 1,
            "align": "center",
            "valign": "vcenter",
            "num_format": "0.00",
        })

        grade_fmt = {}
        for grade, color in self.GRADE_COLORS.items():
            grade_fmt[grade] = workbook.add_format({
                "bold": True,
                "bg_color": color,
                "font_color": "white",
                "border": 1,
                "align": "center",
                "valign": "vcenter",
            })

        # Create sheets
        self._create_summary_sheet(workbook, header_fmt, title_fmt, label_fmt, value_fmt, 
                                   grade_fmt, player_data)
        self._create_serve_analysis_sheet(workbook, header_fmt, label_fmt, value_fmt, player_data)
        self._create_return_analysis_sheet(workbook, header_fmt, label_fmt, value_fmt, player_data)
        self._create_kitchen_sheet(workbook, header_fmt, label_fmt, value_fmt, player_data)
        self._create_best_shots_sheet(workbook, header_fmt, label_fmt, value_fmt, player_data, int(player_data["info"]["player_id"]))
        self._create_raw_data_sheet(workbook, header_fmt, value_fmt, player_data)

        workbook.close()
        print(f"✓ Generated: {output_file}")

    def _create_summary_sheet(self, workbook, header_fmt, title_fmt, label_fmt, value_fmt, 
                              grade_fmt, player_data):
        """Create Summary sheet with player name, grades, and KPIs."""
        ws = workbook.add_worksheet("Summary")
        ws.set_column("A:A", 25)
        ws.set_column("B:B", 20)

        info = player_data["info"]
        
        # Title
        ws.write("A1", f"Player {info['player_id']} Analytics", title_fmt)
        
        # Player Info
        row = 3
        ws.write(row, 0, "Player Name:", label_fmt)
        ws.write(row, 1, info.get("player_name", f"Player {info['player_id']}"), value_fmt)
        
        row += 1
        ws.write(row, 0, "Video ID:", label_fmt)
        ws.write(row, 1, info["vid"], value_fmt)

        # Grades Section
        row += 2
        ws.write(row, 0, "PERFORMANCE GRADES", header_fmt)
        ws.write(row, 1, "", header_fmt)
        
        grades = [
            ("Serve Depth Grade", "serve_depth_grade"),
            ("Serve Height Grade", "serve_height_grade"),
            ("Serve Kitchen Grade", "serve_kitchen_grade"),
            ("Return Depth Grade", "return_depth_grade"),
            ("Return Height Grade", "return_height_grade"),
            ("Return Kitchen Grade", "return_kitchen_grade"),
        ]

        row += 1
        for label, key in grades:
            grade = info[key]
            ws.write(row, 0, label, label_fmt)
            ws.write(row, 1, grade, grade_fmt.get(grade, value_fmt))
            row += 1

        # KPIs Section
        row += 1
        ws.write(row, 0, "KEY PERFORMANCE INDICATORS", header_fmt)
        ws.write(row, 1, "", header_fmt)
        
        shot_stats = self._calculate_shot_stats(player_data["shots"])

        row += 1
        kpis = [
            ("Serve Depth Average (ft)", self._safe_float(info["serve_depth_avg"])),
            ("Serve Height Average (ft)", self._safe_float(info["serve_height_avg"])),
            ("Serve Kitchen %", self._safe_float(info["serve_kitchen_pct"]) * 100),
            ("Return Depth Average (ft)", self._safe_float(info["return_depth_avg"])),
            ("Return Height Average (ft)", self._safe_float(info["return_height_avg"])),
            ("Return Kitchen %", self._safe_float(info["return_kitchen_pct"]) * 100),
            ("Total Serves", shot_stats["serve"]["count"]),
            ("Total Returns", shot_stats["return"]["count"]),
        ]

        for label, value in kpis:
            ws.write(row, 0, label, label_fmt)
            if isinstance(value, int):
                ws.write(row, 1, value, value_fmt)
            else:
                ws.write(row, 1, value, value_fmt)
            row += 1

        # Video Highlights Section (if links are available)
        video_links = self._get_player_video_links(int(info["player_id"]))
        row += 1
        ws.write(row, 0, "VIDEO HIGHLIGHTS", header_fmt)
        ws.write(row, 1, "", header_fmt)

        link_fmt = workbook.add_format({
            "font_color": "#2563EB",
            "underline": 1,
        })

        row += 1
        ws.write(row, 0, "Serve Highlights", label_fmt)
        if video_links["serve"]:
            ws.write_url(row, 1, video_links["serve"], link_fmt, "Open")
        else:
            ws.write(row, 1, "Not available", value_fmt)

        row += 1
        ws.write(row, 0, "Return Highlights", label_fmt)
        if video_links["return"]:
            ws.write_url(row, 1, video_links["return"], link_fmt, "Open")
        else:
            ws.write(row, 1, "Not available", value_fmt)

        row += 1
        ws.write(row, 0, "Best Shots", label_fmt)
        if video_links["best_shots"]:
            ws.write(row, 1, "See below", value_fmt)
            for key, link in video_links["best_shots"]:
                row += 1
                ws.write(row, 0, key.replace("_", " ").title(), label_fmt)
                ws.write_url(row, 1, link, link_fmt, "Open")
        else:
            ws.write(row, 1, "Not available", value_fmt)

    def _create_serve_analysis_sheet(self, workbook, header_fmt, label_fmt, value_fmt, player_data):
        """Create Serve Analysis sheet with depth/height distributions."""
        ws = workbook.add_worksheet("Serve Analysis")
        ws.set_column("A:A", 25)
        ws.set_column("B:B", 15)

        shots = player_data["shots"]
        shot_stats = self._calculate_shot_stats(shots)
        serve_stats = shot_stats["serve"]

        # Header
        ws.write("A1", "SERVE ANALYSIS", header_fmt)
        ws.write("B1", "", header_fmt)

        # Averages
        row = 3
        ws.write(row, 0, "Average Depth (ft):", label_fmt)
        ws.write(row, 1, serve_stats["avg_depth"], value_fmt)

        row += 1
        ws.write(row, 0, "Average Height (ft):", label_fmt)
        ws.write(row, 1, serve_stats["avg_height"], value_fmt)

        row += 1
        ws.write(row, 0, "Total Serves:", label_fmt)
        ws.write(row, 1, serve_stats["count"], value_fmt)

        # Depth Distribution
        row += 2
        ws.write(row, 0, "DEPTH DISTRIBUTION", header_fmt)
        ws.write(row, 1, "Count", header_fmt)

        depth_dist = self._calculate_depth_distribution(shots, "serve")
        row += 1
        for bucket, count in depth_dist.items():
            ws.write(row, 0, bucket, label_fmt)
            ws.write(row, 1, count, value_fmt)
            row += 1

        # Height Distribution
        row += 2
        ws.write(row, 0, "HEIGHT DISTRIBUTION", header_fmt)
        ws.write(row, 1, "Count", header_fmt)

        height_dist = self._calculate_height_distribution(shots, "serve")
        row += 1
        for bucket, count in height_dist.items():
            ws.write(row, 0, bucket, label_fmt)
            ws.write(row, 1, count, value_fmt)
            row += 1

    def _create_return_analysis_sheet(self, workbook, header_fmt, label_fmt, value_fmt, player_data):
        """Create Return Analysis sheet with depth/height distributions."""
        ws = workbook.add_worksheet("Return Analysis")
        ws.set_column("A:A", 25)
        ws.set_column("B:B", 15)

        shots = player_data["shots"]
        shot_stats = self._calculate_shot_stats(shots)
        return_stats = shot_stats["return"]

        # Header
        ws.write("A1", "RETURN ANALYSIS", header_fmt)
        ws.write("B1", "", header_fmt)

        # Averages
        row = 3
        ws.write(row, 0, "Average Depth (ft):", label_fmt)
        ws.write(row, 1, return_stats["avg_depth"], value_fmt)

        row += 1
        ws.write(row, 0, "Average Height (ft):", label_fmt)
        ws.write(row, 1, return_stats["avg_height"], value_fmt)

        row += 1
        ws.write(row, 0, "Total Returns:", label_fmt)
        ws.write(row, 1, return_stats["count"], value_fmt)

        # Depth Distribution
        row += 2
        ws.write(row, 0, "DEPTH DISTRIBUTION", header_fmt)
        ws.write(row, 1, "Count", header_fmt)

        depth_dist = self._calculate_depth_distribution(shots, "return")
        row += 1
        for bucket, count in depth_dist.items():
            ws.write(row, 0, bucket, label_fmt)
            ws.write(row, 1, count, value_fmt)
            row += 1

        # Height Distribution
        row += 2
        ws.write(row, 0, "HEIGHT DISTRIBUTION", header_fmt)
        ws.write(row, 1, "Count", header_fmt)

        height_dist = self._calculate_height_distribution(shots, "return")
        row += 1
        for bucket, count in height_dist.items():
            ws.write(row, 0, bucket, label_fmt)
            ws.write(row, 1, count, value_fmt)
            row += 1

    def _create_kitchen_sheet(self, workbook, header_fmt, label_fmt, value_fmt, player_data):
        """Create Kitchen Performance sheet with role × perspective table."""
        ws = workbook.add_worksheet("Kitchen Performance")
        ws.set_column("A:A", 20)
        ws.set_column("B:E", 18)

        kitchen_data = player_data["kitchen"]

        # Header
        ws.write("A1", "KITCHEN PERFORMANCE", header_fmt)

        # Column headers
        row = 3
        ws.write(row, 0, "Role / Perspective", header_fmt)
        ws.write(row, 1, "Self", header_fmt)
        ws.write(row, 2, "Partner", header_fmt)

        # Organize data by role
        roles = set(k["role"] for k in kitchen_data)
        row = 4

        for role in sorted(roles):
            role_data = [k for k in kitchen_data if k["role"] == role]
            
            ws.write(row, 0, role.title(), label_fmt)
            
            for item in role_data:
                perspective = item["perspective"]
                kitchen_pct = float(item["kitchen_pct"]) * 100
                col = 1 if perspective == "oneself" else 2
                
                ws.write(row, col, f"{kitchen_pct:.1f}%", value_fmt)
            
            row += 1

        # Summary stats
        row += 2
        ws.write(row, 0, "SUMMARY", header_fmt)

        row += 1
        overall_arrivals = sum(int(k["kitchen_arrivals"]) for k in kitchen_data)
        overall_opportunities = sum(int(k["opportunities"]) for k in kitchen_data)
        overall_pct = (overall_arrivals / overall_opportunities * 100) if overall_opportunities > 0 else 0

        ws.write(row, 0, "Total Kitchen Arrivals:", label_fmt)
        ws.write(row, 1, overall_arrivals, value_fmt)

        row += 1
        ws.write(row, 0, "Total Opportunities:", label_fmt)
        ws.write(row, 1, overall_opportunities, value_fmt)

        row += 1
        ws.write(row, 0, "Overall Kitchen %:", label_fmt)
        ws.write(row, 1, overall_pct, value_fmt)

    def _create_best_shots_sheet(self, workbook, header_fmt, label_fmt, value_fmt, player_data, player_id):
        """Create Best Shots sheet with shot descriptions from player_best_shots.csv."""
        ws = workbook.add_worksheet("Best Shots")
        ws.set_column("A:A", 25)
        ws.set_column("B:B", 20)
        ws.set_column("C:C", 20)

        # Header
        ws.write("A1", "BEST SHOTS", header_fmt)
        ws.write("B1", "Winner Type", header_fmt)
        ws.write("C1", "Quality Score", header_fmt)

        # Get best shots for this player
        best_shots = [s for s in self.player_best_shots if int(s["player_id"]) == player_id]

        if best_shots:
            row = 2
            for shot in best_shots:
                rally_idx = shot.get("rally_idx", "")
                shot_idx = shot.get("shot_idx", "")
                winner_type = shot.get("winner_type", "")
                quality = shot.get("quality_overall", "")
                
                ws.write(row, 0, f"Rally {rally_idx}, Shot {shot_idx}", label_fmt)
                ws.write(row, 1, winner_type.title() if winner_type else "", value_fmt)
                ws.write(row, 2, float(quality) if quality else 0, value_fmt)
                row += 1
        else:
            row = 2
            ws.write(row, 0, "No best shots available", label_fmt)
            ws.write(row, 1, "", value_fmt)
            ws.write(row, 2, "", value_fmt)

    def _create_raw_data_sheet(self, workbook, header_fmt, value_fmt, player_data):
        """Create hidden Raw Shot Data sheet."""
        ws = workbook.add_worksheet("Raw Shot Data")
        ws.hide()
        
        ws.set_column("A:J", 18)

        # Column headers
        headers = [
            "Rally", "Shot #", "Shot Type", "Role", "Start (ms)", 
            "End (ms)", "Depth (ft)", "Height (ft)"
        ]
        for col, header in enumerate(headers):
            ws.write(0, col, header, header_fmt)

        # Data rows
        shots = player_data["shots"]
        for row, shot in enumerate(shots, start=1):
            ws.write(row, 0, shot["rally_idx"], value_fmt)
            ws.write(row, 1, shot["shot_idx"], value_fmt)
            ws.write(row, 2, shot["shot_type"], value_fmt)
            ws.write(row, 3, shot["shot_role"], value_fmt)
            ws.write(row, 4, shot["start_ms"], value_fmt)
            ws.write(row, 5, shot["end_ms"], value_fmt)
            ws.write(row, 6, shot["depth"] if shot["depth"] else "", value_fmt)
            ws.write(row, 7, shot["height_over_net"] if shot["height_over_net"] else "", value_fmt)

    def generate_all(self):
        """Generate spreadsheets for all players in data."""
        if not self.player_averages:
            print("Error: player_averages.csv not found or empty. Cannot generate spreadsheets.")
            return
        
        player_ids = set(int(r["player_id"]) for r in self.player_averages)
        for player_id in sorted(player_ids):
            self.generate(player_id)


def main():
    """Generate all player analytics spreadsheets."""
    data_dir = Path(__file__).parent.parent / "data"
    generator = SpreadsheetGenerator(str(data_dir))
    generator.generate_all()


if __name__ == "__main__":
    main()
